CONFIG_PATH: mlflow_artifacts\vits_ljspeech_v2\config.json
MLFLOW_TRACKING_PASSWORD: be1471b0ac3e0b36f1c4a65c2a39364979a1aa96
MLFLOW_TRACKING_URI: https://dagshub.com/sahil.verma/DinoTTS.mlflow
MLFLOW_TRACKING_USERNAME: dinaaksh.aulakh10
MODEL_PATH: mlflow_artifacts\vits_ljspeech_v2\optimized_model.pth
TOGETHER_API_KEY: 383ee051b2cbb563ac497a4dab58b3031607fbef7dc334a07e50fa12585231c1
